// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3pmgKoh07IkJ9OXLv2ecRCsyG3rksrA8',
    appId: '1:162088505695:web:866994c6ee7379b802e6ea',
    messagingSenderId: '162088505695',
    projectId: 'dat-lich-kham-app',
    authDomain: 'dat-lich-kham-app.firebaseapp.com',
    storageBucket: 'dat-lich-kham-app.firebasestorage.app',
    measurementId: 'G-CSBEFKX6X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlyWX8hiHySYIH7F00uCrptsunnlyAKM',
    appId: '1:162088505695:android:6c0b00b90f7abc7602e6ea',
    messagingSenderId: '162088505695',
    projectId: 'dat-lich-kham-app',
    storageBucket: 'dat-lich-kham-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC7lFsI3wEDuVPZ9Td35OUSxB2RvCYOM8',
    appId: '1:162088505695:ios:7df608e27bdb9d1802e6ea',
    messagingSenderId: '162088505695',
    projectId: 'dat-lich-kham-app',
    storageBucket: 'dat-lich-kham-app.firebasestorage.app',
    iosBundleId: 'com.example.datLichKhamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC7lFsI3wEDuVPZ9Td35OUSxB2RvCYOM8',
    appId: '1:162088505695:ios:7df608e27bdb9d1802e6ea',
    messagingSenderId: '162088505695',
    projectId: 'dat-lich-kham-app',
    storageBucket: 'dat-lich-kham-app.firebasestorage.app',
    iosBundleId: 'com.example.datLichKhamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3pmgKoh07IkJ9OXLv2ecRCsyG3rksrA8',
    appId: '1:162088505695:web:a569d99639b1fc1102e6ea',
    messagingSenderId: '162088505695',
    projectId: 'dat-lich-kham-app',
    authDomain: 'dat-lich-kham-app.firebaseapp.com',
    storageBucket: 'dat-lich-kham-app.firebasestorage.app',
    measurementId: 'G-KY30CV59NR',
  );
}
